### ISSUE TITLE
Keine Funktion mehr

### ISSUE THREAD

**Issue by dg0ojo** [mgreg89/node-red-contrib-siro-connector#2]
Momentan keine Funktion mehr.

**Comment by mgreg89** [comment]
Hallo dg0ojo,
seit wann hast du das Problem? Bei mir funktionieren noch Rollos im Haushalt wie immer.
Hast du schon versucht Node-Red neuzustarten? Ansonsten kann ich mir nur vorstellen, dass die Bridge ein Update bekommen hat, dass die Schnittstelle verändert. Welche Version läuft dort bei dir?

**Comment by dg0ojo** [comment]
Guten Morgen,Hab das Problem seit einer Woche circa. Das Rollo an sich funktioniert mit Google etc. Finde in der Connector-App leider keine Firmwareversion.Mit freundlichen GrüßenAlexander LaueAm 10.09.2022 um 23:06 schrieb mgreg89 ***@***.***>:﻿
Hallo dg0ojo,
seit wann hast du das Problem? Bei mir funktionieren noch Rollos im Haushalt wie immer.
Hast du schon versucht Node-Red neuzustarten? Ansonsten kann ich mir nur vorstellen, dass die Bridge ein Update bekommen hat, dass die Schnittstelle verändert. Welche Version läuft dort bei dir?

**Comment by mgreg89** [comment]
Die Version der Connector-App findest du über das Menü. Dort einfach oben auf dein Profil klicken und dann unten auf "Über". Ich bin bei Version 2.6.5.1201 (39).

Ansonsten kann man noch die Firmware-Version der Bridge checken: Menü -> Standort -> Zahnrad deiner Bridge -> nochmal Zahnrad deiner Bridge -> und dann unter Firmware. Meine derzeit: 0.8.2.0

**Comment by dg0ojo** [comment]
Mit freundlichen GrüßenAlex LaueGesendet vom iPhone.Am 11.09.2022 um 11:39 schrieb mgreg89 ***@***.***>:﻿
Die Version der Connector-App findest du über das Menü. Dort einfach oben auf dein Profil klicken und dann unten auf "Über". Ich bin bei Version 2.6.5.1201 (39).
Ansonsten kann man noch die Firmware-Version der Bridge checken: Menü -> Standort -> Zahnrad deiner Bridge -> nochmal Zahnrad deiner Bridge -> und dann unter Firmware. Meine derzeit: 0.8.2.0
