### ISSUE TITLE
Keine Rückmeldung

### ISSUE THREAD

**Issue by ManuelWaldmann** [mgreg89/node-red-contrib-siro-connector#4]
Hi,

Erstmal großen Dank für deine Arbeit.
Verbindung lief problemlos, und die Rollos fahren wie sie sollen.
Leider bekomme ich aber keinerlei Rückmeldung der Motoren, wie Batteriestatus, aktuelle Positionen usw.
Auch keine Fehlermeldung. Im Debug Node taucht nichts auf.
Vielleicht kannst du da helfen.

Connector Version: 2.7.3.0112 (50)
Firmware Version: A1.0.2_B0.1.4

Grüße
Manuel

**Comment by mgreg89** [comment]
Hey @ManuelWaldmann

Danke, dass du die Contrib nutzt und den Fehler hier gemeldet hast 👍 

Ich habe Version 1.3.1 auf NPM veröffentlicht. Sie sollte das Problem beheben 😃 

Grüße
Gregor

**Comment by ManuelWaldmann** [comment]
Hi @mgreg89 

Vielen Dank!
Alles klappt. 😎

Grüße
Manuel

**Comment by dg0ojo** [comment]
Kann mir jemand sagen, warum ich zwar per NPM die 1.3.1 installiert bekomme, Node-Red aber beharrlich die 1.2.8 anzeigt?
